import {
  RiBankLine,
  RiBookMarkedLine,
  RiBubbleChartLine,
  RiFileChartLine,
  RiFolderAddLine,
  RiFundsBoxLine,
  RiIncreaseDecreaseLine,
  RiListOrdered,
  RiMoneyDollarCircleLine,
  RiNodeTree,
  RiOrganizationChart,
  RiShoppingCartLine,
  RiWallet3Line,
} from '@remixicon/react';

export const homeCardItems = [
  {
    key: 'managementAreas',
    title: 'Áreas de Gestión',
    description: '...',
    href: '/app/areas-de-gestion',
    icon: RiBankLine,
    iconColor: 'text-lime-900',
    iconBackgroundColor: 'bg-lime-50',
  },
  {
    key: 'costCenters',
    title: 'Centros de Costos',
    description: '...',
    href: '/app/centros-de-costos',
    icon: RiListOrdered,
    iconColor: 'text-blue-900',
    iconBackgroundColor: 'bg-blue-50',
  },
  {
    key: 'directorates',
    title: 'Direcciones / Unidades',
    description: '...',
    href: '/app/direcciones',
    icon: RiNodeTree,
    iconColor: 'text-yellow-900',
    iconBackgroundColor: 'bg-yellow-50',
  },
  {
    key: 'chartAccounts',
    title: 'Plan de Cuentas',
    description: '...',
    href: '/app/plan-de-cuentas',
    icon: RiBubbleChartLine,
    iconColor: 'text-red-900',
    iconBackgroundColor: 'bg-red-50',
  },
  {
    key: 'pladeco',
    title: 'PLADECO',
    description: '...',
    href: '/app/pladeco',
    icon: RiBookMarkedLine,
    iconColor: 'text-green-900',
    iconBackgroundColor: 'bg-green-50',
  },
  {
    key: 'investmentInitiatives',
    title: 'Iniciativas de Inversión',
    description: '...',
    href: '/app/iniciativas-de-inversion',
    icon: RiIncreaseDecreaseLine,
    iconColor: 'text-violet-900',
    iconBackgroundColor: 'bg-violet-50',
  },
  {
    key: 'departments',
    title: 'Departamentos',
    description: '...',
    href: '/app/departamentos',
    icon: RiOrganizationChart,
    iconColor: 'text-orange-900',
    iconBackgroundColor: 'bg-orange-50',
  },
  {
    key: 'shoppingPortal',
    title: 'Portal de Compras',
    description: '...',
    href: '/app/portal-de-compras',
    icon: RiShoppingCartLine,
    iconColor: 'text-amber-900',
    iconBackgroundColor: 'bg-amber-50',
  },
  {
    key: 'budgetSheets',
    title: 'Fichas de Presupuesto',
    description: '...',
    href: '/app/fichas-de-presupuesto',
    icon: RiFileChartLine,
    iconColor: 'text-teal-900',
    iconBackgroundColor: 'bg-teal-50',
  },
  {
    key: 'financingSources',
    title: 'Fuentes de Financiamiento',
    description: '...',
    href: '/app/fuentes-de-financiamiento',
    icon: RiMoneyDollarCircleLine,
    iconColor: 'text-indigo-900',
    iconBackgroundColor: 'bg-indigo-50',
  },
  {
    key: 'improvementProjects',
    title: 'Proyectos de Mejoramiento',
    description: '...',
    href: '/app/proyectos-de-mejoramiento',
    icon: RiFolderAddLine,
    iconColor: 'text-fuchsia-900',
    iconBackgroundColor: 'bg-fuchsia-50',
  },
  {
    key: 'reports',
    title: 'Informes',
    description: '...',
    href: '/app/informes',
    icon: RiFundsBoxLine,
    iconColor: 'text-cyan-900',
    iconBackgroundColor: 'bg-cyan-50',
  },
  {
    key: 'incomeBudget',
    title: 'Presupuesto de Ingresos',
    description: '...',
    href: '/app/presupuesto-de-ingresos',
    icon: RiWallet3Line,
    iconColor: 'text-rose-900',
    iconBackgroundColor: 'bg-rose-50',
  },
];
