import {
  RiBankLine,
  RiBookMarkedLine,
  RiBubbleChartLine,
  RiFileChartLine,
  RiFolderAddLine,
  RiFundsBoxLine,
  RiHome4Fill,
  RiIncreaseDecreaseLine,
  RiListOrdered,
  RiMoneyDollarCircleLine,
  RiNodeTree,
  RiOrganizationChart,
  RiShoppingCartLine,
  RiWallet3Line,
} from '@remixicon/react';

export const sidebarItemsApp = [
  {
    key: 'home',
    title: 'Home',
    href: '/app/home',
    current: false,
    icon: RiHome4Fill,
    iconColor: 'text-slate-800',
  },
  {
    key: 'managementAreas',
    title: 'Áreas de Gestión',
    href: '/app/areas-de-gestion',
    current: false,
    icon: RiBankLine,
    iconColor: 'text-lime-900',
  },
  {
    key: 'costCenters',
    title: 'Centros de Costos',
    href: '/app/centros-de-costos',
    current: false,
    icon: RiListOrdered,
    iconColor: 'text-blue-900',
  },
  {
    key: 'directorates',
    title: 'Direcciones / Unidades',
    href: '/app/direcciones',
    current: false,
    icon: RiNodeTree,
    iconColor: 'text-yellow-900',
  },
  {
    key: 'chartAccounts',
    title: 'Plan de Cuentas',
    href: '/app/plan-de-cuentas',
    current: false,
    icon: RiBubbleChartLine,
    iconColor: 'text-red-900',
  },
  {
    key: 'pladeco',
    title: 'PLADECO',
    href: '/app/pladeco',
    current: false,
    icon: RiBookMarkedLine,
    iconColor: 'text-green-900',
    children: [
      {
        key: 'specificObjetives',
        title: 'Específicos',
        href: '/app/pladeco/especificos',
        current: false,
        icon: RiMoneyDollarCircleLine,
        iconColor: 'text-indigo-900',
      },
      {
        key: 'strategicObjetives',
        title: 'Estratégicos',
        href: '/app/pladeco/estrategicos',
        current: false,
        icon: RiMoneyDollarCircleLine,
        iconColor: 'text-indigo-900',
      },
    ],
  },
  {
    key: 'investmentInitiatives',
    title: 'Iniciativas de Inversión',
    href: '/app/iniciativas-de-inversion',
    current: false,
    icon: RiIncreaseDecreaseLine,
    iconColor: 'text-violet-900',
  },
  {
    key: 'departments',
    title: 'Departamentos',
    href: '/app/departamentos',
    current: false,
    icon: RiOrganizationChart,
    iconColor: 'text-orange-900',
  },
  {
    key: 'shoppingPortal',
    title: 'Portal de Compras',
    href: '/app/portal-de-compras',
    current: false,
    icon: RiShoppingCartLine,
    iconColor: 'text-amber-900',
  },
  {
    key: 'budgetSheets',
    title: 'Fichas de Presupuesto',
    href: '/app/fichas-de-presupuesto',
    current: false,
    icon: RiFileChartLine,
    iconColor: 'text-teal-900',
    children: [
      {
        key: 'investmentInitiatives',
        title: 'Iniciativas de inversion',
        href: '/app/fichas-de-presupuesto/iniciativas-de-inversion',
        current: false,
        icon: RiMoneyDollarCircleLine,
        iconColor: 'text-indigo-900',
      },
      {
        key: 'improvementProject',
        title: 'Proyectos de mejora',
        href: '/app/fichas-de-presupuesto/proyectos-de-mejora',
        current: false,
        icon: RiMoneyDollarCircleLine,
        iconColor: 'text-indigo-900',
      },
    ],
  },
  {
    key: 'financingSources',
    title: 'Fuentes de Financiamiento',
    href: '/app/fuentes-de-financiamiento',
    current: false,
    icon: RiMoneyDollarCircleLine,
    iconColor: 'text-indigo-900',
  },
  {
    key: 'improvementProjects',
    title: 'Proyectos de Mejoramiento',
    href: '/app/proyectos-de-mejoramiento',
    current: false,
    icon: RiFolderAddLine,
    iconColor: 'text-fuchsia-900',
  },
  {
    key: 'reports',
    title: 'Informes',
    href: '/app/informes',
    current: false,
    icon: RiFundsBoxLine,
    iconColor: 'text-cyan-900',
    children: [
      {
        key: 'budgetary',
        title: 'Presupuestarios',
        href: '/app/informes/presupuestarios',
        current: false,
        icon: RiMoneyDollarCircleLine,
        iconColor: 'text-indigo-900',
      },
      {
        key: 'accountants',
        title: 'Contables',
        href: '/app/informes/contables',
        current: false,
        icon: RiMoneyDollarCircleLine,
        iconColor: 'text-indigo-900',
      },
    ],
  },
  {
    key: 'incomeBudget',
    title: 'Presupuesto de Ingresos',
    href: '/app/presupuesto-de-ingresos',
    current: false,
    icon: RiWallet3Line,
    iconColor: 'text-rose-900',
  },
];
